export const errorType = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
  CONFIG_ERROR: "CONFIG_ERROR",
  AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR",
  TOKEN_EXPIRE_ERROR: "TOKEN_EXPIRE_ERROR",
};
