import React from "react";
import { ThemeProvider } from "next-themes";
import type { AppProps } from "next/app";
import Head from "next/head";
import "react-date-range/dist/styles.css"; // main style file
import "react-date-range/dist/theme/default.css"; // theme css file
import "../assets/css/global.css";
import ApolloProviderWrapper from "../graphQL";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>School System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <ApolloProviderWrapper>
        <ThemeProvider>
          <Component {...pageProps} />
        </ThemeProvider>
      </ApolloProviderWrapper>
      {/* <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script> */}
    </>
  );
}
export default MyApp;
