import { ITableDataType } from "./types";

export const mockData: ITableDataType<{
  id: number;
  Name: string;
  Job: string;
  company: string;
  location: string;
  lastLogin: string;
  favoriteColor: string;
}> = {
  col: [
    {
      id: 1,
      name: "",
    },
    {
      id: 2,
      name: "Name",
    },
    {
      id: 3,
      name: "Job",
    },
    {
      id: 4,
      name: "Company",
    },
    {
      id: 5,
      name: "Location",
    },
    {
      id: 6,
      name: "Random date",
    },
    {
      id: 7,
      name: "Favorite Color",
    },
  ],
  data: [
    {
      id: 1,
      Name: "Cy Ganderton",
      Job: "Quality Control Specialist",
      company: "Littel, Schaden and Vandervort",
      location: "Canada",
      lastLogin: "12/16/2020",
      favoriteColor: "Blue",
    },
    {
      id: 2,
      Name: "Hart Hagerty",
      Job: "Desktop Support Technician",
      company: "Zemlak, Daniel and Leannon",
      location: "United States",
      lastLogin: "12/5/2020",
      favoriteColor: "Purple",
    },
    {
      id: 3,
      Name: "Brice Swyre",
      Job: "Tax Accountant",
      company: "Carroll Group",
      location: "China",
      lastLogin: "8/15/2020",
      favoriteColor: "Red",
    },
    {
      id: 4,
      Name: "Marjy Ferencz",
      Job: "Office Assistant I",
      company: "Rowe-Schoen",
      location: "Russia",
      lastLogin: "3/25/2021",
      favoriteColor: "Crimson",
    },
    {
      id: 5,
      Name: "Yancy Tear",
      Job: "Community Outreach Specialist",
      company: "Wyman-Ledner",
      location: "Brazil",
      lastLogin: "5/22/2020",
      favoriteColor: "Indigo",
    },
    {
      id: 6,
      Name: "Irma Vasilik",
      Job: "Editor",
      company: "Wiza, Bins and Emard",
      location: "Venezuela",
      lastLogin: "12/8/2020",
      favoriteColor: "Purple",
    },
    {
      id: 7,
      Name: "Meghann Durtnal",
      Job: "Staff Accountant IV",
      company: "Schuster-Schimmel",
      location: "Philippines",
      lastLogin: "2/17/2021",
      favoriteColor: "Yellow",
    },
    {
      id: 8,
      Name: "Sammy Seston",
      Job: "Accountant I",
      company: "O'Hara, Welch and Keebler",
      location: "Indonesia",
      lastLogin: "5/23/2020",
      favoriteColor: "Crimson",
    },
    {
      id: 9,
      Name: "Lesya Tinham",
      Job: "Safety Technician IV",
      company: "Turner-Kuhlman",
      location: "Philippines",
      lastLogin: "2/21/2021",
      favoriteColor: "Maroon",
    },
    {
      id: 10,
      Name: "Zaneta Tewkesbury",
      Job: "VP Marketing",
      company: "Sauer LLC",
      location: "Chad",
      lastLogin: "6/23/2020",
      favoriteColor: "Green",
    },
    {
      id: 11,
      Name: "Andy Tipple",
      Job: "Librarian",
      company: "Hilpert Group",
      location: "Poland",
      lastLogin: "7/9/2020",
      favoriteColor: "Indigo",
    },
    {
      id: 12,
      Name: "Sophi Biles",
      Job: "Recruiting Manager",
      company: "Gutmann Inc",
      location: "Indonesia",
      lastLogin: "2/12/2021",
      favoriteColor: "Maroon",
    },
    {
      id: 13,
      Name: "Florida Garces",
      Job: "Web Developer IV",
      company: "Gaylord, Pacocha and Baumbach",
      location: "Poland",
      lastLogin: "5/31/2020",
      favoriteColor: "Purple",
    },
    {
      id: 14,
      Name: "Maribeth Popping",
      Job: "Analyst Programmer",
      company: "Deckow-Pouros",
      location: "Portugal",
      lastLogin: "4/27/2021",
      favoriteColor: "Aquamarine",
    },
    {
      id: 15,
      Name: "Moritz Dryburgh",
      Job: "Dental Hygienist",
      company: "Schiller, Cole and Hackett",
      location: "Sri Lanka",
      lastLogin: "8/8/2020",
      favoriteColor: "Crimson",
    },
    {
      id: 16,
      Name: "Reid Semiras",
      Job: "Teacher",
      company: "Sporer, Sipes and Rogahn",
      location: "Poland",
      lastLogin: "7/30/2020",
      favoriteColor: "Green",
    },
    {
      id: 17,
      Name: "Alec Lethby",
      Job: "Teacher",
      company: "Reichel, Glover and Hamill",
      location: "China",
      lastLogin: "2/28/2021",
      favoriteColor: "Khaki",
    },
    {
      id: 18,
      Name: "Aland Wilber",
      Job: "Quality Control Specialist",
      company: "Kshlerin, Rogahn and Swaniawski",
      location: "Czech Republic",
      lastLogin: "9/29/2020",
      favoriteColor: "Purple",
    },
    {
      id: 19,
      Name: "Teddie Duerden",
      Job: "Staff Accountant III",
      company: "Pouros, Ullrich and Windler",
      location: "France",
      lastLogin: "10/27/2020",
      favoriteColor: "Aquamarine",
    },
    {
      id: 20,
      Name: "Lorelei Blackstone",
      Job: "Data Coordiator",
      company: "Witting, Kutch and Greenfelder",
      location: "Kazakhstan",
      lastLogin: "6/3/2020",
      favoriteColor: "Red",
    },
  ],
};
